repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: inv lint
        language: system
        stages: [commit, merge-commit]
        always_run: true
        pass_filenames: false